import Head from 'next/head'
import { ethers } from "ethers";
import React, { useState } from 'react';
import Image from 'next/image'
import Card from '../components/Card'
import DeployCard from '../components/DeployCard'
import MintStateCard from '../components/MintStateCard'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {

  const connectWallet = async () => {
    const provider = new ethers.providers.Web3Provider(window.ethereum, "any");
    // Prompt user for account connections
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner();
    let connectedAddress = await signer.getAddress();
    console.log("Account:", connectedAddress);
    document.getElementById("walletButton").innerHTML = shortenAddress(connectedAddress);
  }

  function shortenAddress(connectedAddress) {
    let addressStart = connectedAddress.slice(0, 5);
    let addressEnd = connectedAddress.slice(38, 42);
    let shortenedAddress = addressStart + "..." + addressEnd;
    return shortenedAddress;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar connectWallet={connectWallet}/>
      <DeployCard />
      <Card />
      <MintStateCard />

    </div>
  )
}
