import Head from 'next/head'
import abi from '../utils/NFT.json';
import { ContractFactory, ethers } from "ethers";
import React, { useState } from 'react';
import Image from 'next/image'
import Card from '../components/Card'
import DeployCard from '../components/DeployCard'
import MintStateCard from '../components/MintStateCard'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {

  const IPFS_IMAGE_METADATA_URI = `ipfs://QmQdPYTY8yArgVmMJK319e75rsi91bwtUF5JsSF9CLnEYe/`
  const contractABI = abi.abi;
  const contractBytecode = abi.bytecode;

  const connectWallet = async () => {
    const provider = new ethers.providers.Web3Provider(window.ethereum, "any");
    // Prompt user for account connections
    await provider.send("eth_requestAccounts", []);
    const signer = provider.getSigner();
    let connectedAddress = await signer.getAddress();
    console.log("Account:", connectedAddress);
    document.getElementById("walletButton").innerHTML = shortenAddress(connectedAddress);
  }

  function shortenAddress(connectedAddress) {
    let addressStart = connectedAddress.slice(0, 5);
    let addressEnd = connectedAddress.slice(38, 42);
    let shortenedAddress = addressStart + "..." + addressEnd;
    return shortenedAddress;
  }

  async function deploy() {
    try {
      if (window.ethereum) {
        const provider = new ethers.providers.Web3Provider(window.ethereum, "any");
        const signer = provider.getSigner();
        // get contract to deploy and deploy
        // const NFT = await hre.ethers.getContractFactory("NFT");
        let NFT = new ContractFactory(contractABI, contractBytecode, signer);
        const nft = await NFT.deploy("Famous Paintings", "PAINT", IPFS_IMAGE_METADATA_URI);
        await nft.deployed();
        console.log("NFT Contract deployed to ", nft.address);
        document.getElementById("contractAddress").innerHTML = nft.address;
      }
    }
    catch (error) {
      console.log(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar connectWallet={connectWallet}/>
      <DeployCard deploy={deploy}/>
      <Card />
      <MintStateCard />

    </div>
  )
}
